### ISSUE TITLE
Lack of policies about supported Nixpkgs releases

### ISSUE THREAD

**Issue by ShamrockLee** [instantOS/nix#32]
**Describe the bug**

It is unclear which release version of Nixpkgs this project is intended to support.

Nixpkgs is a moving target with stable branch-out twice a year. "Out-of-tree" environment-related Nix projects (such as [Home Manager](https://github.com/nix-community/home-manager), [nix-darwin](https://github.com/LnL7/nix-darwin),  and [NixOnDroid](https://github.com/t184256/nix-on-droid)) often have release branches that tracks the correspoding Nixpkgs release branches, and the unstable branch (master / dev) tracks the master branch of Nixpkgs. It would be grea if this project adopts the release branch workflow.

Under such context, it would be better to check the `flake.lock` file (of each branch) into the Git tree to mark the known-work revisions. Home Manager made the decision some years ago. Sorry for my previous suggestion to ignore it (https://github.com/instantOS/instantNIX/pull/28#issuecomment-1108722467).

BTW, Nixpkgs 20.09 is EOL'ed three years ago. Using such an EOL'ed version exposes the system under known security vulnerabilities.

Before submitting a new bug, please **double-check**:

 - [X] No other existing issue covers this bug
 - [X] The bug is not yet scheduled on the [roadmap](https://github.com/instantOS/instantOS/projects/1)
 - [X] It is indeed related to instantNIX and not caused by bugs in an external (upstream) project, such as nixpkgs / NUR
 - [X] You are **not** out for tech-support or help using instantOS (you'll get faster responses in our [Discord](https://discord.io/instantos) or the other outlets on our [support page](https://instantos.io/support))

You help us save time and energy by making sure. Remember instantOS is free and we maintain it in our precious spare time. 

**To Reproduce**
<details>
</details>

**Screenshots**

**Additional Information:**
<details>
 - Nixos: yes / no [are you running NixOS or just using the Nix package manager on another distribution]
 - Achitectrue: amd64 [the architecture of the system that shows the bug]
 - Commit: 38950e5 [a commit hash of instantNIX that shows the bug]
</details>

**Comment by con-f-use** [comment]
Hi. Thanks for you unwavering interest in instantNIX and taking the time to write up a detailed issue. It warms my heart. The sad reality of open source work is that the amount peoples' free time and their interests shift. There have only ever been one and a quarter people working on instandOS/NIX with any sort of regularity. The quarter being me and the full time benni. I have a day job and benni is a full time student now. The only chance OSS software has for longtime success is community. If the community grows large enough and active enough, people step up when such shifts happen and full-time, dedicated people might make a living of the project and get some happiness from it. If that doesn't happen and the passion wanes, and that is fine, too. The project  will be there for others to pick up or learn from because it is free and open. Sadly, the former has not (yet!) happened for instantOS/NIX and so, we're stuck with the latter.

What I want to say by that is:

> It would be grea[t] if this project adopts the release branch workflow.

100% would be, but that requires constant effort and maintenance, that so far nobody is up to exerting. You might notice that instantOS has never left its beta phase and not many people are interested in it anymore. There is no lack of ideas about would could be done better or more, just a lack of people with the time and priority to implement them.

> BTW, Nixpkgs 20.09 is EOL'ed three years ago.

Yes, we're aware that `20.09` means it's from the month of September in the year 2020 :wink:

> Using such an EOL'ed version exposes the system under known security vulnerabilities.

It goes without saying, that people should only use outdated software, if they know what they are doing. Given that there is almost no user base, that it is fairly obvious, that we're not meant for any form of sensitive use and that new users would need to be fairly tech-savy to make it to a working system, I don't feel particularly guilt-tripped into action on that point.

Long story short, consider it mostly unmaintained, although I'm happy to review and merge pull requests, but don't expect that to go at a particularly fast pace. I'm also sure, that if we talked to benni, he would welcome additional reviewers and maintainers.

**Comment by ShamrockLee** [comment]
Sorry for the inconvenience, and thank you for maintaining this project!

**Comment by con-f-use** [comment]
Not an inconvenience at all, I'd love to do more and regularly, but it's just not in the cards.
